CREATE TABLE public.investor_profiles (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
  title                 TEXT,
  bio                   TEXT,
  linkedin_url          TEXT,
  website_url           TEXT,
  location              TEXT,
  investment_thesis     TEXT,
  sectors               TEXT[] DEFAULT '{}',
  stage_preference      TEXT[] DEFAULT '{}',
  geography             TEXT[] DEFAULT '{}',
  ticket_size_min       NUMERIC,
  ticket_size_max       NUMERIC,
  angel_title           TEXT,
  fund_name             TEXT,
  fund_size_usd         NUMERIC,
  bank_name             TEXT,
  lending_products      TEXT[] DEFAULT '{}',
  nbfc_name             TEXT,
  funding_types         TEXT[] DEFAULT '{}',
  risk_tolerance        TEXT,
  office_name           TEXT,
  co_investment_interest TEXT,
  parent_company        TEXT,
  cvc_name              TEXT,
  strategic_sectors     TEXT[] DEFAULT '{}',
  partnership_types     TEXT[] DEFAULT '{}',
  innovation_focus      TEXT[] DEFAULT '{}',
  deal_flow_paused      BOOLEAN DEFAULT FALSE,
  deal_limit_per_week   INT DEFAULT 20,
  hidden_sectors        TEXT[] DEFAULT '{}',
  response_rate         TEXT DEFAULT 'N/A',
  actively_investing    BOOLEAN DEFAULT TRUE,
  portfolio_count       INT DEFAULT 0,
  is_verified           BOOLEAN DEFAULT FALSE,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_investor_profile_user ON public.investor_profiles(user_id);
CREATE INDEX idx_investor_sectors      ON public.investor_profiles USING gin(sectors);
CREATE INDEX idx_investor_stages       ON public.investor_profiles USING gin(stage_preference);
